[app]
# debug release  test
mode = 'debug'
timezone = 'PRC'
rootPath = ""

[server]
address = '127.0.0.1:9999'
readTimeout = 15
writeTimeout = 60
idleTimeout = 15

[db]
debug = true
host = '127.0.0.1'
charset = 'utf8'
username = 'root'
password = 'root'
database = 'juzizm_ppt'
tablePrefix = 'jz_'
maxIdleConns = 10
maxOpenConns = 1000
connMaxLifeTime = 30

[log]
saveLogs = true
single = true
level = 'info'
path = './logs'
logName = 'cgo'

[tpl]
enable = false
path = './template/*'

[jwt]
secret = '123^&%$#*((*JHYYU5645GCVBkljh'
signingMethod = ''

[redis]
network="tcp"
address="127.0.0.1:6379"
password=""
db=0